"""добавление дат регистрации и последней игры

Revision ID: d48984e0df27
Revises: c9967df94cf8
Create Date: 2025-01-31 17:07:49.737862

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d48984e0df27"
down_revision: Union[str, None] = "c9967df94cf8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "casino_users", sa.Column("registrated", sa.DateTime(), nullable=False)
    )
    op.add_column(
        "casino_users", sa.Column("last_game", sa.DateTime(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("casino_users", "last_game")
    op.drop_column("casino_users", "registrated")
    # ### end Alembic commands ###
